.PHONY: repl test

# Start REPL with project dependencies
repl:
	clojure -M

# Run tests with Kaocha test runner
test:
	clojure -M:test:test-runner

# Start REPL with test dependencies included (Generated by Calva)
repl-test:
	clojure -Sdeps '{:deps {nrepl/nrepl {:mvn/version,"1.3.1"},cider/cider-nrepl {:mvn/version,"0.55.4"}}}' -M:test -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware]"
