name: Checks

on:
  pull_request:
  push:
    branches:
      - main
      - master
  workflow_call:

jobs:
  lint-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/cache-clojure-deps
        with:
          key-label: 'lint'
      - uses: jdx/mise-action@v3.3.1
        with:
          install_args: "babashka@1.12.206 clj-kondo@2025.06.05 java@temurin-21.0.2+13.0.LTS clojure@1.12.1.1550"
      - name: Lint
        run: bb deps && bb lint-init && bb lint

  outdated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/cache-clojure-deps
        with:
          key-label: 'outdated'
      - uses: jdx/mise-action@v3.3.1
        with:
          install_args: "babashka java clojure"
      - name: Outdated deps
        run: bb deps && bb outdated-check

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/cache-clojure-deps
        with:
          key-label: 'tests'
      - uses: jdx/mise-action@v3.3.1
        with:
          install_args: "babashka java clojure"
      - name: Run tests
        run: bb deps && bb test
