name: Clojure CI
on: push

jobs:
  clojure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Clojure Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2
            ~/.gitlibs
          key: cache-${{ hashFiles('**/deps.edn') }}
          restore-keys: clojure-deps-

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: 1.11.1.1165    # Clojure CLI based on tools.deps
          clj-kondo: 2025.06.05 # Clj-kondo

      - name: Run Unit tests
        run: clojure -M:test:runner

      - name: "Lint with clj-kondo"
        run: clj-kondo --lint deps.edn src test